### ISSUE TITLE
The SSL connection could not be established, see inner exception. System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.

### ISSUE THREAD

**Issue by Tejp0306** [nopSolutions/FedEx-plugin-for-nopcommerce#12]
#Hi Folks,

We are using this to integrate in our app, it works fine until we are testing it on our local dev environment. However, after hosting the build integration on the IIS server, We are receiving the below error: Feel free to share if anyone have any clues:
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Nop.Plugin.Shipping.Fedex.API.OAuth.OAuthClient.API_AuthorizationAsync(String content_type, FullSchema body, CancellationToken cancellationToken) in D:\OHB_Repo\SourceCode\nopCommerce_4.60.2\src\Plugins\Nop.Plugin.Shipping.Fedex\API\OAuth\OAuthClient.cs:line 132
   at Nop.Plugin.Shipping.Fedex.Services.FedexService.GetAccessTokenAsync() in D:\OHB_Repo\SourceCode\nopCommerce_4.60.2\src\Plugins\Nop.Plugin.Shipping.Fedex\Services\FedexService.cs:line 291 
  ```
   
🤔

**Comment by skoshelev** [comment]
Hi, @Tejp0306!

This issue isn't directly related to the plugin; even the stack trace shows that the HttpClient class is throwing an exception.
What version of Windows are you using? For example, [this article](https://learn.microsoft.com/en-us/answers/questions/764378/authentication-failed-because-the-remote-party-sen) mentions a widespread issue on Windows Server 2012 R2. Perhaps updating the server with the latest updates from Microsoft will help.
